name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1 
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_push
      run: |
        echo "Starting Docker build and push..."
        docker buildx build --push --quiet --tag bitcoindevproject/public-inbox:latest --no-cache .
        echo "Docker push completed successfully."
      continue-on-error: true

    - name: Verify Docker Push
      run: |
        echo "Checking if Docker image exists in DockerHub..."
        if docker pull bitcoindevproject/public-inbox:latest; then
          echo "Docker push was successful."
        else
          echo "Docker push failed!"
          exit 1
        fi

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        id: railway_deploy
        run: |
          echo "Starting Railway deployment..."
          railway up --service public-inbox
          echo "Railway deployment completed successfully."
        continue-on-error: true

      - name: Verify Railway Deployment
        run: |
          echo "Checking Railway deployment status..."
          if railway status; then
            echo "Railway deployment was successful."
          else
            echo "Railway deployment failed!"
            exit 1
          fi
